name: Release
on:
  push:
    branches:
      - main
      - v2

jobs:
  release:
    name: gh-action-create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read version
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
